[package]
name = "tri-2048"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[features]

[dependencies]
rand = "0.4.2"
lazy_static = "1.0.0"

# pancurses = { version = "0.15.0", optional = true }
